In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [43]:
df=pd.read_csv("tested.csv")

In [44]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [45]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
413        False     False   False  False  False   True  False  False   False   
414        False     False   False  False  False  False  False  False   False   
415        False     False   False  False  False  False  False  False   False   
416        False     False   False  False  False   True  False  False   False   
417        False     False   False  False  False   True  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False   True     False  
2    False   True     False  
3    False   True     False  
4    False   True     False  
..     ...    ...       ...  
413  False   True     False  
414  False  False     False  
415  False   True     False  
416  False   True     False  
417  False   True     False  

[418 rows x 12 columns]

In [46]:
new_df=df.drop(["PassengerId","Name","Parch","Ticket","Cabin","Embarked"],axis=1)

In [47]:
new_df

Survived  Pclass     Sex   Age  SibSp      Fare
0           0       3    male  34.5      0    7.8292
1           1       3  female  47.0      1    7.0000
2           0       2    male  62.0      0    9.6875
3           0       3    male  27.0      0    8.6625
4           1       3  female  22.0      1   12.2875
..        ...     ...     ...   ...    ...       ...
413         0       3    male   NaN      0    8.0500
414         1       1  female  39.0      0  108.9000
415         0       3    male  38.5      0    7.2500
416         0       3    male   NaN      0    8.0500
417         0       3    male   NaN      1   22.3583

[418 rows x 6 columns]

In [48]:
dummy=pd.get_dummies(new_df["Sex"],drop_first=True,prefix="Sex",dtype=int)
dummy

Sex_male
0           1
1           0
2           1
3           1
4           0
..        ...
413         1
414         0
415         1
416         1
417         1

[418 rows x 1 columns]

In [49]:
new_df=pd.concat([new_df,dummy],axis=1)


In [50]:
new_df.drop("Sex",axis=1,inplace=True)


In [61]:
new_df["Age"].fillna(new_df["Age"].mean(),inplace=True)


In [63]:
new_df["Survived"].fillna(new_df["Survived"].mean(),inplace=True)

In [64]:
new_df["Sex_male"].fillna(new_df["Sex_male"].mean(),inplace=True)

In [65]:
new_df["Fare"].fillna(new_df["Fare"].mean(),inplace=True)

In [66]:
new_df["Pclass"].fillna(new_df["Pclass"].mean(),inplace=True)

In [67]:
new_df["SibSp"].fillna(new_df["SibSp"].mean(),inplace=True)

In [71]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()
np_df=scalar.fit_transform(new_df)

In [72]:
new_df=pd.DataFrame(np_df,columns=['Survived',	'Pclass',	'Sex',	'Age',	'SibSp',	'Fare'])

In [77]:
x=new_df.drop('Survived',axis=1)
y=new_df['Survived']


0    0.0
1    1.0
2    0.0
3    0.0
4    1.0
Name: Survived, dtype: float64

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, 
                                                    random_state=1)

In [80]:
from sklearn.linear_model import LogisticRegression

In [82]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [94]:
predictions=logmodel.predict(x_test)
predictions

array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.])

In [96]:
np.array(y_test)

array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.])

# SCORE OF THE MODEL

In [86]:
logmodel.score(x_test,y_test)

1.0

In [87]:
from sklearn.metrics import confusion_matrix

In [88]:
accuracy=confusion_matrix(y_test,predictions)

In [89]:
accuracy

array([[58,  0],
       [ 0, 26]], dtype=int64)

In [90]:
from sklearn.metrics import accuracy_score

In [91]:
accuracy=accuracy_score(y_test,predictions)
accuracy

1.0

In [92]:
from sklearn.metrics import classification_report

In [93]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        58
         1.0       1.00      1.00      1.00        26

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

